events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://rotation:8080/api/v1/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ~ ^/(radio\.mp3|stream|listen) {
            proxy_pass http://icecast:8000;

            proxy_buffering off;
            proxy_read_timeout 3600s;
        }

        location /status-json.xsl {
            proxy_pass http://icecast:8000/status-json.xsl;
        }
    }
}
